#!/usr/bin/env python3
"""Write a sourceable, machine-local configuration for the README commands."""
import argparse
import ipaddress
import json
import os
from pathlib import Path
import re
import shlex
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]


def ask(label, default=''):
    answer = input(f'{label}' + (f' [{default}]' if default else '') + ': ').strip()
    return answer or default


def render(values):
    lines = ['# Generated by scripts/configure_artifact.py; source from Bash.',
             '# Local settings only; do not include this file in the public artifact.']
    lines += [f'export {key}={shlex.quote(str(value))}' for key, value in values.items()]
    lines += [
        'export WORKSPACE_SETUP="${ARTIFACT_ROOT}/install/setup.bash"',
        'export RMW_IMPLEMENTATION=rmw_fastrtps_cpp',
        'export ROS_DOMAIN_ID=77',
        'unset ROS_LOCALHOST_ONLY ROS_AUTOMATIC_DISCOVERY_RANGE ROS_STATIC_PEERS',
        'export RP_EXP_RESULTS_ROOT="${ARTIFACT_ROOT}/results/${ARTIFACT_RUN_ID}"',
        'export RP_EXP_BAGS_ROOT="${ARTIFACT_ROOT}/bags/${ARTIFACT_RUN_ID}"',
        'export NIC="${ARTIFACT_NIC}"',
        'export RP_BIN="${ARTIFACT_ROOT}/.tools/bin/rp"',
        'source "${ARTIFACT_ROOT}/common/environment.sh"',
        'rp_exp_source_setup "${ROS_SETUP}" || return',
        'if [[ -f "${WORKSPACE_SETUP}" ]]; then',
        '  rp_exp_source_setup "${WORKSPACE_SETUP}" || return',
        'fi',
    ]
    return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--ros-distro', choices=['humble', 'jazzy'],
                        help='default: ROS_SETUP / ROS_DISTRO, then installed Humble or Jazzy')
    parser.add_argument('--network', action='store_true', help='prompt for peer IP, NIC, platform and run label')
    parser.add_argument('--output', type=Path, default=ROOT / '.artifact-env.sh',
                        help='configuration to create or replace (default: .artifact-env.sh)')
    args = parser.parse_args()
    if args.ros_distro:
        setup = Path(f'/opt/ros/{args.ros_distro}/setup.bash')
    elif os.environ.get('ROS_SETUP'):
        setup = Path(os.environ['ROS_SETUP']).expanduser().resolve()
    else:
        choices = list(dict.fromkeys([os.environ.get('ROS_DISTRO', ''), 'humble', 'jazzy']))
        setup = next((Path(f'/opt/ros/{name}/setup.bash') for name in choices
                      if name and Path(f'/opt/ros/{name}/setup.bash').is_file()), None)
    if setup is None or not setup.is_file():
        parser.error('install ROS 2 first (README.md#first-time-setup), or set ROS_SETUP to its setup.bash')
    values = dict(ARTIFACT_ROOT=ROOT, ROS_SETUP=setup,
                  ARTIFACT_PEER='', ARTIFACT_NIC='lo', ARTIFACT_LINK='wired',
                  ARTIFACT_PLATFORM='pc', ARTIFACT_RUN_ID='s1-pilot')
    if args.network:
        try:
            peer = str(ipaddress.IPv4Address(ask('Other machine data-link IPv4 address')))
            result = subprocess.run(['ip', '-j', 'route', 'get', peer],
                                    capture_output=True, text=True, check=True, timeout=5)
            routes = json.loads(result.stdout)
            suggested = routes[0].get('dev', '') if routes else ''
            nic = ask('Data interface on THIS machine', suggested)
            if nic == 'lo' or '/' in nic or not Path(f'/sys/class/net/{nic}/statistics/rx_bytes').is_file():
                raise ValueError('choose an existing non-loopback data interface')
            link = ask('Link label (wired/wireless)', 'wired')
            platform = ask('THIS machine platform (pc/rpi/jetson)', 'pc')
            label = ask('Run label (use the same label on both machines)', 's1-pilot')
            if link not in ('wired', 'wireless') or platform not in ('pc', 'rpi', 'jetson'):
                raise ValueError('unsupported link or platform')
            if not re.fullmatch(r'[A-Za-z0-9][A-Za-z0-9_-]*', label):
                raise ValueError('run label must use letters, digits, underscores or hyphens')
            values.update(ARTIFACT_PEER=peer, ARTIFACT_NIC=nic, ARTIFACT_LINK=link,
                          ARTIFACT_PLATFORM=platform, ARTIFACT_RUN_ID=label)
        except (ValueError, OSError, subprocess.SubprocessError, EOFError) as error:
            parser.error(str(error))
    destination = args.output.expanduser().resolve()
    destination.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(mode='w', dir=destination.parent, delete=False) as stream:
        temporary = Path(stream.name)
        stream.write(render(values))
    try:
        temporary.replace(destination)
    finally:
        temporary.unlink(missing_ok=True)
    print(f'Configuration: {destination}')
    print(f'ROS setup: {setup}')
    if args.network:
        print(f'Peer: {values["ARTIFACT_PEER"]}; NIC: {values["ARTIFACT_NIC"]}; run: {values["ARTIFACT_RUN_ID"]}')
    print(f'Next: source {shlex.quote(str(destination))}')
    print('This config loads ROS and sets shell variables; it does not start experiments or tune the machine.')


if __name__ == '__main__':
    main()
